### ISSUE TITLE
managing release/unpacked

### ISSUE THREAD

**Issue by Bigsy** [binaryage/chromex-sample#1]
Sorry for raising an issue about this, not so much a problem but a query and wasn't sure where ask it. I've started using this template and made good progress with it, its great having figwheel support for extension development. 

The extension I'm working on is unfortunately quite html heavy and I was just wondering if it down to me to keep the contents of release and unpacked folder in sync? I'm an experienced clojure dev but new to clojurescript/js and chrome extensions, just wondering if its a hole in my workflow and/or if there is anything I can do to automate that bit.

**Comment by darwin** [comment]
That symlink trick does not work for you? 

I share images folder between `unpacked` and `release` using symlinked folder here:
https://github.com/binaryage/chromex-sample/blob/master/resources/unpacked/images

**Comment by Bigsy** [comment]
Thanks, I meant more the collection of the html I have. Is the usual workflow to solely develop in unpacked then when you want to build some kind of release you manually copy over your html and remove unneeded script references?

**Comment by darwin** [comment]
So you html files differ between unpacked and release? I assumed they didn't.

If yes, then you probably need some kind of automated script to generate release versions from debug versions. You could use some templating system or simply write a small bash script doing some dirty regex replacements in text files. This really depends on your needs and tools you are familiar with. I'm not aware of any usual workflow.

**Comment by Bigsy** [comment]
No my vanilla html doesn't, but I thought your template needed extra js in the html for devtools and or figwheel integration? Maybe I'm misunderstanding I'm new to the web side of things.... 

I'm just editing my html quite a bit and its just been a little bit of a pain copying it over, just throught I was maybe missing a trick. I guess perhaps, I can write something myself to make it less painful. Cheers.

**Comment by darwin** [comment]
I'm confused. If you are editing your files under development then you don't have to care about release folder. You have your unpacked folder loaded as unpacked extension in your chrome and after editing your html files you should see updated version in the browser thanks to figwheel (if all is correctly set up).

You care about release folder only when you build your "final" extension with :advanced optimizations and you want to test it before publishing. From chrome's point of view, release folder contains a new extension.
