### ISSUE TITLE
popup reload

### ISSUE THREAD

**Issue by deg** [binaryage/chromex-sample#10]
Both Chrome extensions and Figwheel use plumbing magic that I don't understand yet, so I definitely don't  understand how the two work together. ...

I've put some re-frame components into code built from this sample. Basically, a call to `reagent.core/render` from `...core/init!`.

Everything works. re-frame does its stuff, Figwheel does its stuff. If I change a component, it gets recompiled.  If i introduce an error, Figwheel shows a warning over the popup. Etc. All good.

The one thing that is not working is that if I change a component, it does not get re-rendered immediately. I need to close the popup and re-open it.  Not a really big deal; just a click on the icon and a right-click to re-inspect. But, surprising and intrusive in the workflow.

Is there some reason that this should not work? Or am I doing something wrong?

**Comment by darwin** [comment]
I'm sorry I'm not that much familiar with recent figwheel and reagent. I think this is not related to popup scenario. I wonder if it behaved the same in the context of a normal page...

**Comment by deg** [comment]
Nope. On normal page, Figwheel behavior is magically beautiful, refreshing page components as it reloads behind the scenes.

I tend to agree with you that this is not a real limitations of popups, but rather something silly that I skipped. But, I don't have an easy way to narrow down the problem, and the pain is still fairly small. So, I don't think I'm going to solve this unless I get lucky and run across the answer.

Dunno if you should keep this open in the hope that someone knows the answer; or close it, since it's at a dead-end.

**Comment by deg** [comment]
I took another look at this today.

The problem is the `^:figwheel-no-load` you put at https://github.com/binaryage/chromex-sample/blob/f25bb857f1e7dab586c917854921256b382285ec/src/popup/chromex_sample/popup.cljs#L1

Do you remember why you needed to add it? Removing it fixes the problem and doesn't seem to do any harm (in my one minute of testing).

**Comment by darwin** [comment]
We can remove it. It is not very important. The goal was to prevent multiple init! calls in case of figwheel reload of the popup.cljs file. I was under impression that this init call has to be called only once.

**Comment by deg** [comment]
I don't know enough. So far, I've seen no ill effects from allowing the reload. But, my app is still small enough not to be a real test. In particular, it would suffer no real harm if the re-frame app-db was reloaded every time I saved a file.

Worse: I don't fully understand why changing this fixed my problem. In the standard re-frame template, the init happens from a call in the index.html file.  Does figwheel force a full reload of that file? If not, then the standard template is not calling the init again, yet still works correctly. ...leaving me puzzled.

(I assume that you moved the call to the .cljs file to avoid chrome extension security restrictions?)
