### ISSUE TITLE
Is the current version of this template broken?

### ISSUE THREAD

**Issue by Folcon** [binaryage/chromex-sample#11]
I thought it might have been something I did when I updated, but I'm currently getting this if I run `lein fig`, `lein content` and load it as an unpacked extension in the chrome console.

<img width="634" alt="screen shot 2018-04-24 at 16 07 48" src="https://user-images.githubusercontent.com/123055/39196428-03fe80bc-47da-11e8-9558-969e0d7e7f29.png">

I haven't got time right now to chase it down, but I'll try adding more when I get a moment.

This is the contents of `base.js`.
```
goog.require("devtools.preload");
goog.require("figwheel.connect.build_popup");
goog.require("chromex_sample.popup");
```

**Comment by darwin** [comment]
Yes, it broke when I did bump figwheel without actually checking errors in browser console.
