### ISSUE TITLE
More sophisticated popup?

### ISSUE THREAD

**Issue by deg** [binaryage/chromex-sample#4]
Do you have (or know of) any projects built on `chromex-sample` that render the popup from ClojureScript.  (I'm not sure how the tooling needs to change for this, and would love to avoid wheel-reinventing).

My ideal would be something using re-frame, FWIW.

**Comment by darwin** [comment]
I'm sorry I don't know about any code example showing re-frame (reagent) integration.

But I believe it should be exactly the same as for traditional web pages. Popup.html is a normal web context with some extra extension-related functionality on top. That is the idea behind chrome extensions design - you don't have to do anything special and simply develop your UI as you would do it for a normal web page: https://developer.chrome.com/extensions/overview#pages.

**Comment by deg** [comment]
ok, thanks

**Comment by deg** [comment]
For the benefit of the next person sharing my brain-bubble... This was a silly question that I asked.
I could have (and now have) simply done a GitHub search:  `chromex AND re-frame` in the search box and then click on `code`.  Currently, there are 24 hits, some of which look like exactly what I wanted.

**Comment by darwin** [comment]
Great! Closing.

**Comment by deg** [comment]
I'v built a minimal example of using re-frame in the popup of this sample app: https://github.com/deg/chromex-sample/tree/re-frame-in-popup

I can submit it to you as a PR, if you want. But, it's probably outside the scope of what you want in this project.

While doing so, I also noticed that the other forks in https://github.com/binaryage/chromex-sample/network had each scratched the same itch: adding some GUI to the popup in this sample app, using reagent or other frameworks.  This may be an indication of wider demand; maybe someone should put them all together and create a suite of sample extensions.

**Comment by darwin** [comment]
Thanks for the offer. But this is really outside the scope of this example. I also plan to make this example project more minimalistic. Right now this project also contains some configuration to be used by me as a test project during chromex development. Which may be confusing for less experienced ClojureScript users.

I would maybe add a section into readme with other more realistic usage examples. I'm open to pull requests if you want to take stab at it. Feel free to put it at the top of the readme file.

**Comment by deg** [comment]
I agree with your direction to make the example more minimal.  I think it's best to wait until after you've done that before adding more complexity in the readme. But, give me a ping when you are ready, and I'll be happy to write something.

That will also give me a chance to figure out where my example should live. Currently, it is in a branch of a fork of your project .... obviously not ideal.
Meanwhile, I'll leave it there. Anyone who needs it and does any plausible Google search will probably find it via this issue.
