### ISSUE TITLE
lein package vs images

### ISSUE THREAD

**Issue by deg** [binaryage/chromex-sample#7]
Unless I'm being faked out, there is a problem with `lein package`.

In the release build, it leaves `images` as a dangling symbolic link to `../shared/images`, which does not exist under `releases`.

**Comment by deg** [comment]
This was apparently a Mac vs Linux issue.

I've submitted a PR. I've verified that the script works on Ubuntu 16.04.

I was not able to do a full test on a Mac, but I did test the `'cp` flags there, so I don't think this causes any regression on Mac.

**Comment by darwin** [comment]
I think we can close this one. You are correct and the change should work on macOS. Thanks for the patch.
